services:
  otel-lgtm:
    container_name: otel-lgtm
    image: grafana/otel-lgtm:0.5.0
    ports:
      - 127.0.0.1:3000:3000 # Grafana Web UI
      - 127.0.0.1:4317:4317 # OpenTelemetry Collector (gRPC)
      - 127.0.0.1:4318:4318 # OpenTelemetry Collector (HTTP)
    volumes:
      - $PWD/container/grafana:/data/grafana
      - $PWD/container/prometheus:/data/prometheus
      - $PWD/container/loki:/loki
    environment:
      - GF_PATHS_DATA=/data/grafana
