{
 "title": "HTTP Server Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "rate(http_server_duration_milliseconds_count[1m])",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count[1m])",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "rate(http_server_duration_milliseconds_count[$__rate_interval])",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_count[$__rate_interval])",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "{.service.name=\"rolldice\"}",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "limit": 20,
     "query": "{.service.name=\"rolldice\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}